### ISSUE TITLE
Replace lodash merge with actual `eslint`'s `util.mergeConfig` via `extends`.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/eslint-config-defaults#13]
There are some subtle differences with how eslint `extend`'s configs vs. a brute force `_.merge()`. (E.g., `plugins` are special-cased and handled differently than normal keys).

We should look to use eslint's first class `extends` + under-the-hood `mergeConfig`, especially once eslint comes in as a `devDependency` so that we don't accidentally queue up subtle merge bugs later (wherein composed configurations here would behave differently than library uses doing `extends` of the same underlying configs manually).

**Comment by baer** [comment]
https://github.com/eslint/eslint/search?utf8=%E2%9C%93&q=mergeConfig

I'm not sure what function you're referring to. I'll look further but I do not believe that eslint exposes their merge function. That said, merge allows for a customizer function which I will likely use in it's place.

**Comment by ryan-roemer** [comment]
Actually, I meant don't merge in this project at all. Use only eslint config options of extends to do all the work.

**Comment by ryan-roemer** [comment]
Let's have this project actually be _eslint configs_ and not try to duplicate on our own what eslint does internally. Let's just let eslint handle all merging itself.

**Comment by chaseadamsio** [comment]
PR coming.

**Comment by chaseadamsio** [comment]
Alright, all set on this one.
