### ISSUE TITLE
Error: Cannot find module 'eslint-config-defaults/configurations/airbnb'

### ISSUE THREAD

**Issue by rtorino** [walmartlabs/eslint-config-defaults#18]
I've installed `eslint-config-defaults` and created `.eslintrc` file in the root of my project directory. This is the content of my `.eslintrc` file:

```js
{
  "extends": "defaults"
}
```

When I ran `eslint` on my project directory, I got the following error:
```
Error: Cannot find module 'eslint-config-defaults/configurations/airbnb'
```

I am using `node v0.12.7`, `npm v2.11.3` and `eslint v0.24.1`

**Comment by rtorino** [comment]
I figured out the issue and able to solve it.

**Comment by baer** [comment]
@rtorino What was the issue here? defaults shouldn't have any references to airbnb. The default config should mirror what `eslint --init` gives you. I'd like to be able to document issues if there are any.
