### ISSUE TITLE
Error: cannot read config file

### ISSUE THREAD

**Issue by mendlik** [walmartlabs/eslint-config-defaults#34]
I think this problem may interest you https://github.com/AtomLinter/linter-eslint/issues/213

**Comment by ryan-roemer** [comment]
Confirmed:

```
---
"extends":
  - "defaults"
```

Does _not_ work. We do have `main` in `package.json` pointing to `./configurations/eslint.js` which would seem to work, but doesn't.

Not sure exactly, what's up but could we add another import in perhaps `ROOT/index.js` file to see if the import from eslint is just ignoring the `package.json` somehow?

Or maybe something else?

/cc @baer @chaseadamsio
