### ISSUE TITLE
rules/eslint/style/walmart.js not compatible with strict mode, though marked as such

### ISSUE THREAD

**Issue by JanNorden** [walmartlabs/eslint-config-defaults#54]
rules/eslint/style/walmart.js contains a duplicate field name:

    "space-before-keywords": 0,
    // require or disallow space before blocks
    "space-before-blocks": [2, "always"],
    // require or disallow space before function opening parenthesis
    "space-before-function-paren": [2, {"anonymous": "always", "named": "never" }],
    // require a space before certain keywords (fixable)
    "space-before-keywords": [2, "always"],

GIving the following error when running eslint:

/src/scripts/provision-test-environment/node_modules/eslint-config-defaults/rules/eslint/style/walmart.js:122
 "space-before-keywords": [2, "always"],
 ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Cannot read config package: eslint-config-defaults/rules/eslint/style/walmart
Error: Duplicate data property in object literal not allowed in strict mode

**Comment by JanNorden** [comment]
Created a pull request for this.

**Comment by ryan-roemer** [comment]
@JanNorden -- There's actually multiple instances of this. I'm fixing and adding eslint of _the configs themselves_ to travis CI.

/cc @baer

**Comment by JanNorden** [comment]
Thanks for the quick reply. Guessed there might be more after seeing the
other pull request. Looking forward to the fixes.

2016-01-12 16:08 GMT+01:00 Ryan Roemer <notifications@github.com>:

> @JanNorden <https://github.com/JanNorden> -- There's actually multiple
> instances of this. I'm fixing and adding eslint of *the configs
> themselves* to travis CI.
>
> /cc @baer <https://github.com/baer>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walmartlabs/eslint-config-defaults/issues/54#issuecomment-170941683>
> .
>



-- 
/Jan Norden
