### ISSUE TITLE
Any interest in tracking Node.js core style?

### ISSUE THREAD

**Issue by kevinoid** [walmartlabs/eslint-config-defaults#59]
Although it's not currently packaged as a shareable config, the style used by the Node core team may be of interest, particularly for code which provides polyfills for Node features (either planned features or backports), but also generally for code which runs on Node.

Would that fall within this project's scope?  If so, is there any interest in including it?  If so, I could work up a PR.

Thanks for considering,
Kevin

**Comment by baer** [comment]
Hi @kevinoid it certainly is well within the project's scope and I'd happily take a PR. However, I'm cautious about taking on another unofficial config. Is there an example of the node core config that I could have a look at?

**Comment by kevinoid** [comment]
Hey @baer, I can definitely understand that.  Another argument against inclusion is that the coding convention and rationales don't appear to be documented outside of the `.eslintrc`, so it is not really publicized.  But it is definitely an authority source that people are likely to use for various purposes.  It won't hurt my feelings either way.

The current ESLint configuration being used by Node core is at https://github.com/nodejs/node/blob/master/.eslintrc  I didn't come across any other style guidelines in the contributor documentation, but I may have missed something.

**Comment by baer** [comment]
I actually think a PR would be great IF you can be assured that they're running eslint 2.x+. In the 1.x version there were a bunch of hidden defaults which would be annoying to track down. If it's 1.x and that config is all there is to it that should be quick to write and easy to maintain.

Thanks for the suggestion!

**Comment by kevinoid** [comment]
Unfortunately, it looks like they are running [a copy of ESLint 1.10.3](https://github.com/nodejs/node/tree/master/tools/eslint).  Presumably they will upgrade to 2.0 once it is released.  Would it make sense to wait until then to consider adding it?

**Comment by baer** [comment]
Sorry... I meant 1.0. 2.x is still in beta. It was the 0.x -> 1.x that made that change.

**Comment by kevinoid** [comment]
Gotcha.  Great!  I'll work up a PR.

**Comment by baer** [comment]
:zap: :zap: :zap: :zap: :zap: :zap: :zap: :zap: :zap: 

Thanks for being a contributor!

:zap: :zap: :zap: :zap: :zap: :zap: :zap: :zap: :zap:

**Comment by kevinoid** [comment]
Sure thing.  It's the least I can do, since I requested it.  Any thoughts on what it should be named?  Just `node` seems ambiguous with the `node` ESLint environment name or Node rules section or with a style that is "the one suggested for Node.js development".  Maybe `node_core`, `nodeCore`, or `nodecore` (since they are valid identifiers, as opposed to `node-core`, which might make a better filename)?

**Comment by kevinoid** [comment]
Given the file-centric uses and current naming scheme, hyphen separated seems preferable.  I also realized "core" is probably a poor choice, "runtime" seems most accurate as it is used in the project description and is unambiguous.

Unless you object, I'll use `node-runtime` for the rule and configuration filenames.

**Comment by baer** [comment]
Closed by #62
