### ISSUE TITLE
docs(error): AirBnb/ES6 requires `eslint-plugin-react` and `babel-eslint`

### ISSUE THREAD

**Issue by uglow** [walmartlabs/eslint-config-defaults#65]
Hi Ryan,

I'm building a Yeoman generator that uses a few of the eslint plugins in this package, and just started my integration testing. I'm getting `Cannot find module 'eslint-plugin-react'` warnings when using this config:
```
{
  "extends": "defaults/configurations/airbnb/es6"
}
```

The way I read current `readme.md`, it indicates that there is no additional dependencies required for this config.

Adding both `eslint-plugin-react` and `babel-eslint` fixes the issue.

**Comment by ryan-roemer** [comment]
Hi @uglow 

We've got https://github.com/walmartlabs/eslint-config-defaults#dependencies which states:

###### Dependencies

- Any Walmart config (`defaults/configurations/walmart/<suffix>`) - [eslint-plugin-filenames](https://github.com/selaux/eslint-plugin-filenames)
- Any React config (`<prefix>-react`) - [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react), [babel-eslint](https://github.com/babel/babel-eslint)
- Any ES-next config (`es6-<suffix>`) - [babel-eslint](https://github.com/babel/babel-eslint)

I think that would cover `babel-eslint`

@baer -- Do we need to add a more nuanced explanation for AirBnB `es6` also needing `eslint-plugin-react`?

**Comment by ryan-roemer** [comment]
@baer  -- **Confirmed** there is an error with needing the `eslint-plugin-react`. We have this line https://github.com/walmartlabs/eslint-config-defaults/blob/master/configurations/airbnb/es5.js#L11

```js
    "defaults/rules/react/airbnb"
```

Which should **not** be part of the "AirBnB ES5 rules" I'm guessing.
