### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [walmartlabs/eslint-config-defaults#80]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by ryan-roemer** [comment]
Hi @amilajack -- this repo is deprecated in favor of https://github.com/walmartlabs/eslint-config-walmart Maybe ask there and see if there are some takers? Thanks!

**Comment by amilajack** [comment]
@ryan-roemer thanks for the heads up!
