### ISSUE TITLE
Switch all properties in JS configs to double quotes.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/eslint-config-defaults#9]
Normally, it is an open issue / team preference to do double vs. single quotes. However, I can see a very common use case of someone wanting to copy and paste segments of some of the configs in this repo into either JS or JSON. If we switch to (and enforce) double quotes this will work seamlessly.

**Comment by baer** [comment]
Yea that sounds good.

However, I hope people are not copy pasting stuff out of the inside of the repo. Kinda misses the point.

**Comment by ryan-roemer** [comment]
> Kinda misses the point.

Actually, I think it's a great starting point (the internal "off" configs for example) of someone to start for their own overrides for their specific configs and have a "one stop shop" for everything in a programmatically accessible fashion. And, as a way to see "here's everything!" from a file perspective.

Nothing says rough like searching and typing out all the overrides (after import) manually and trying to infer them by groups yourself...

**Comment by baer** [comment]
True, that makes sense. I just hope that there are enough complete config options that a typical eslintrc file only has a few lines in it. Anyway, it's done and in develop. It'll go out when I finish the React plugin stuff this week.

**Comment by baer** [comment]
https://github.com/walmartlabs/eslint-config-defaults/commit/e32d4a5ada150f2e86e829d5f27cd30066071182

Done :)
